# Generated by Django 5.2.4 on 2026-02-13 09:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Recording', max_length=255)),
                ('source_type', models.CharField(choices=[('live', 'Live Recording'), ('upload', 'Uploaded Video')], default='live', max_length=20)),
                ('status', models.CharField(choices=[('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='recording', max_length=20)),
                ('original_video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('processed_video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.FloatField(default=0.0, help_text='Duration in seconds')),
                ('fps', models.FloatField(default=24.0)),
                ('resolution_width', models.IntegerField(default=640)),
                ('resolution_height', models.IntegerField(default=480)),
                ('total_frames', models.IntegerField(default=0)),
                ('suspicious_count', models.IntegerField(default=0)),
                ('normal_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Recording',
                'verbose_name_plural': 'Video Recordings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('label', models.CharField(choices=[('normal', 'Normal'), ('suspicious', 'Suspicious')], db_index=True, max_length=20)),
                ('confidence', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('video_path', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.FloatField(default=0.0, help_text='Duration of suspicious activity in seconds')),
                ('bounding_box', models.JSONField(default=dict, help_text='Bounding box coordinates {x1, y1, x2, y2}')),
                ('frame_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='detection.videorecording')),
            ],
            options={
                'verbose_name': 'Detection Event',
                'verbose_name_plural': 'Detection Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['label', 'timestamp'], name='detection_d_label_280550_idx'), models.Index(fields=['confidence'], name='detection_d_confide_8a8281_idx')],
            },
        ),
    ]
